always build container on import
warewulf/warewulf pull request #1143
Opened 2024-03-18 13:20 UTC by mslacken

Removed also the --setdefault option for `wwctl container build`
as implict profile manipultion should be avoided

Signed-off-by: Christian Goll <cgoll@suse.com>

2024-03-21 03:16 UTC, anderbubble commented
Rebased on main.

2024-03-21 03:46 UTC, anderbubble requested changes

2024-03-21 03:46 UTC, anderbubble commented on internal/app/wwctl/container/imprt/root.go
>  	baseCmd.PersistentFlags().BoolVar(&SetDefault, "setdefault", false, "Set this container for the default profile")
If you're going to remove SetDefault in `container build`, you should also remove it in `container import`.

It also needs to be removed from `ContainerImport` and `ContainerBuild`.

2024-03-21 03:51 UTC, anderbubble commented on internal/app/wwctl/container/imprt/root.go
>  	baseCmd.PersistentFlags().BoolVar(&SetDefault, "setdefault", false, "Set this container for the default profile")
Also please remove it from the documentation.

2024-11-05 14:21 UTC, mslacken commented
Rebased, please check again @anderbubble

2024-11-05 14:41 UTC, mslacken commented
Drop if for now. Rethinking this.

2024-11-05 14:41 UTC, closed without merging