Dracut boot refinement
warewulf/warewulf pull request #1269
Opened 2024-06-18 15:47 UTC by jeburks2

## Description of the Pull Request (PR):

The new dracut boot method bloated /proc/cmdline, and exposed asset-tag and uuid to unprivileged users. This PR moves the parsing of dracut URIs from iPXE to the dracut script pase-wwinit.sh, using dmidecode to obtain asset-tag and uuid, leaving only the IP and port of the warewulf server in /proc/cmdline. 

Additionally, it forces runtime overlays to be pulled from a static local port (986) to allow dracut boot to be used with secure mode. Port 986 is used instead of 987 to prevent a race condition of the system releasing the port before wwclient starts and tries to bind to 987. 

Lastly, add the required curl, cpio and now dmidecode packages to warewulf.spec for warewulf-dracut subpackage 

## This fixes or addresses the following GitHub issues:

 - Fixes #1261 

## Before submitting a PR, make sure you have done the following:

- [ x] Signed off on all commits (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [ x] Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/main/contributing/contributing.html)
- [ x ] Added changes to the [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) if necessary
- [ x ] Updated [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) if necessary
- [ x ] Based this PR against the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [ x ] Added myself as a contributor to the [Contributors File](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)

2024-06-19 15:30 UTC, anderbubble commented
Let's confirm that dmidecode is available on all architectures, including ppc.

2024-07-05 17:19 UTC, anderbubble commented
Rebased to main.

2024-07-05 19:41 UTC, anderbubble requested changes
@jeburks2 I've been reviewing this today for hoped inclusion in v4.5.5; but I think I'm going to push it to v4.5.6. At the very least, I think I found a typo bug that was missed, and it also wasn't ported to the grub side.

I spent some time working on suggested modifications. You can find those here: https://github.com/anderbubble/warewulf/tree/dracut-boot-refinement

Let me know what you think.

2024-07-17 15:12 UTC, jeburks2 commented
Thanks for catching that typo, @anderbubble  oops 🤦

The only issue I see is that assetKey and UUID are still left in /proc/cmdline for anyone to see, which is part of what this hopes to solve. However, in some additional testing, our Xen VMs return "Not Defined" for `dmidecode -s chassis-asset-tag`, and that space breaks the URI. 

What you have is a more stable solution for now. I would still like to explore a solution that keeps assetKey and UUID hidden

2024-08-03 00:01 UTC, anderbubble commented
> Let's confirm that dmidecode is available on all architectures, including ppc.

It is not.

https://download.rockylinux.org/pub/rocky/9.4/BaseOS/ppc64le/os/Packages/d/

2024-08-03 00:10 UTC, anderbubble commented
I opened #1351 and asked for a review over there.

2024-09-04 05:48 UTC, anderbubble commented
Closing in favor of #1370.

2024-09-04 05:49 UTC, closed without merging