create soft links:
warewulf/warewulf pull request #1303
Opened 2024-07-12 14:31 UTC by mslacken

create soft link with templates

2024-10-29 17:24 UTC, anderbubble requested changes
I _finally_ think I understand what this is for.

I left some comments in the requested changes. Let me know what you think.

2024-10-29 17:24 UTC, anderbubble commented on overlays/wwinit/rootfs/etc/localtime.ww
> +{{ ImportLink "/etc/localtime" }}
Can you move this to a new overlay? Something like `localtime` maybe, unless there's another one that makes sense.

2024-10-29 17:24 UTC, anderbubble commented on internal/pkg/overlay/funcmap.go
> +}
Could this be replaced with a value that reads the target of a symlink, which could then be passed to the other symlink function? That justifies both functions (by using them both in the example localtime use case) and is more flexible for other templates later.

2024-10-29 17:24 UTC, anderbubble commented on internal/pkg/overlay/overlay.go
> +						} else if len(filenameFromTemplate) != 0 {
This implicitly uses the symlink value if it exists, ignoring any `file` directive. I think specifying both `symlink` and `file` should be an error. Frankly, if there's a `symlink` directive and there's anything else generated that _isn't_ the `symlink` directive, I think that should probably be an error.

2024-10-29 17:25 UTC, anderbubble commented
Rebased to main.

2024-11-08 10:11 UTC, mslacken commented
rebased

2024-11-15 02:40 UTC, anderbubble commented
Rebased to main.

2024-11-15 22:14 UTC, anderbubble approved these changes
@mslacken I added tests for the "localtime" overlay and made it configurable. If you approve, I'll go ahead and merge.

2024-12-18 22:17 UTC, anderbubble commented
Merging as discussed in 18 December 2024 TSC meeting.

2024-12-18 22:17 UTC, merged

2024-12-21 04:10 UTC, anderbubble commented
Closed #1060