Split overlays into discrete functionality
warewulf/warewulf pull request #1306
Opened 2024-07-15 22:35 UTC by anderbubble

## Description of the Pull Request (PR):

Split `wwinit` and `generic` into multiple overlays based on their individual functionality.

## This fixes or addresses the following GitHub issues:

- Closes #987

## Before submitting a PR, make sure you have done the following:

- [ ] Signed off on all commits (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [ ] Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/main/contributing/contributing.html)
- [ ] Added changes to the [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) if necessary
- [ ] Updated [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) if necessary
- [ ] Based this PR against the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [ ] Added myself as a contributor to the [Contributors File](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)

2024-07-15 22:36 UTC, anderbubble commented
@griznog and @mslacken this is definitely not done, but I would be very interested in your thoughts on this so far. In particularly, what do you think about where I split the overlays?

2024-07-16 15:31 UTC, griznog commented
Following the manifesto after looking at your breakout of stuff, something jumps out at me for which I am still struggling to find an answer to: how to handle services that interact with other services? `udev` for instance might need to pick up rules for any type of device, each of which might be managed by a different overlay. So should the `udev` overlay collect all these or should each individual overlay drop in it's own `udev` rules? 

It's more pronounced with something like `firewalld` where I need to have things opened for `sshd`, `caddy`, `ondemand`, `nfs-server`, ... Do I collect all those in a `firewalld` overlay or have each drop its rules into `/etc/firewalld/...` and then somehow let the `firewalld` overlay know what needs to be loaded? And if I split out to all the unique overlays, which seems intuitively the correct approach to me, what about support for `iptables-scripts` and `shorewall` and ...? 

Multiply that example by all the similar or worse ones, like setting up upstream authentication which touches PAM, `sssd`, namespaces, ssh, slurm, Samba, joining a domain, ...

It's also be nice if overlays were, to the extent possible, distro-agnostic. That will be really hard as it's super-non-trivial just to figure out what OS a node image is using from the node image itself, so you start that problem out by having to set a tag somewhere and introducing a place for human error.

2024-07-16 16:49 UTC, griznog commented
Also FWIW, I'd consider splitting these out lower priority than getting support for arbitrary YAML in Tags, as splitting becomes much more interesting once complex, nested data structures can be set in the node configs.

2024-09-03 21:20 UTC, anderbubble commented
@griznog I expect you won't find it perfect; but I adjusted the new overlay names to try to focus on what is being configured, rather than just a partial indication of using a given service to configure something. The best example, I think, is `udev.netname` and `systemd.netname`: both of these attempt to configure the system to use the desired network interface names; but one attempts to use udev and the other systemd to accomplish this.

The most broken overlay, in this regard, is currently `fstab`, as it mixes both NFS configuration and Ignition configuration. I have created #1375 to convert this overlay to use systemd mount units, so that they could be split into separate `nfs` and `ignition` overlays.

Let me know if you have any concerns.

2024-09-03 21:20 UTC, anderbubble commented
@mslacken I think this is ready. Please check it out and let me know what you think. I'd like to get this merged so that we can rebase #1020 onto it.

2024-09-06 13:42 UTC, mslacken approved these changes

2024-09-06 13:46 UTC, mslacken requested changes
The PR doesn't apply any more after the merge of #1380 as there also the tests for the overlays were changed. Can you rebase?

2024-09-06 15:06 UTC, anderbubble commented
Will do!

2024-09-06 17:18 UTC, anderbubble commented
@mslacken rebase is done. Let me know if you have any further concerns.

2024-09-09 06:53 UTC, mslacken approved these changes

2024-09-09 14:32 UTC, mslacken commented
Moving the templates to own overlays is a huge benefit and we should get this merged soon.
Unfortunately the testing is not in the way I would like it.
I propose to have the tests for the overlay rendering in the same place as the overlay itself. This fits much better in the go testing framework, see #1384 as. POC
I know this will need some rework for this PR, but I think its worth the price.

2024-09-09 15:42 UTC, anderbubble commented
I appreciate the feedback, @mslacken. I like the idea in theory, as I understand it, and I will look at it to see what it would take to incorporate.

2024-09-14 04:29 UTC, anderbubble commented
@mslacken I incorporated your example from #1384. The added per-overlay flexibility made it easier to get even more of the overlays tested.

Let me know what you think.

2024-09-14 15:07 UTC, anderbubble commented
I just realized that I neglected to update warewulf.spec to omit the `internal` directories; we don't need/want to deploy the tests with the binary RPMs.

2024-09-14 19:41 UTC, anderbubble commented
> I just realized that I neglected to update warewulf.spec to omit the `internal` directories; we don't need/want to deploy the tests with the binary RPMs.

Done. Looks like I actually needed to change `Makefile`, not `warewulf.spec`.

2024-09-18 17:46 UTC, anderbubble commented
@mslacken I rebased on main. Ready to merge?

2024-09-27 12:59 UTC, merged