enhance the user syncing function
warewulf/warewulf pull request #1358
Opened 2024-08-07 10:25 UTC by JasonYangShadow

## Description of the Pull Request (PR):

Added --syncuser flag to shell command to enhance the user sync function. exec command supports --syncuser command but to trigger it, it requires userdbChanged && SyncUser flag set. shell command can now pass --syncuser flag to exec command to trigger it.

## This fixes or addresses the following GitHub issues:

 - Fixes #1344

## Before submitting a PR, make sure you have done the following:

- [ ] Signed off on all commits (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [ ] Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/main/contributing/contributing.html)
- [ ] Added changes to the [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) if necessary
- [ ] Updated [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) if necessary
- [ ] Based this PR against the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [ ] Added myself as a contributor to the [Contributors File](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)

2024-08-07 10:25 UTC, JasonYangShadow commented
@anderbubble 
please check this comment before review this PR
https://github.com/warewulf/warewulf/issues/1344#issuecomment-2270706904

2024-09-04 17:41 UTC, anderbubble commented
Moved PR to target main and rebased onto current main.

2024-09-04 18:52 UTC, anderbubble requested changes

2024-09-04 18:52 UTC, anderbubble commented on internal/app/wwctl/container/exec/main.go
> +	}
I don't think this should be necessary; `SyncUser` should already be the value from `--syncuser`.

2024-09-04 18:52 UTC, anderbubble commented on internal/app/wwctl/container/exec/main.go
> +		return time.Unix(int64(unixStat.Mtim.Sec), int64(unixStat.Mtim.Nsec))
I agree that mtime is probably the better time stat here; but now I'm realizing that my bug report wasn't true in the first place. I'll comment further in #1344.

2024-09-15 05:46 UTC, anderbubble commented
@JasonYangShadow as I said, my original bug report in #1344 ended up being a misunderstanding; but I still liked the changes in this PR. I made some minor changes. Let me know what you think of my alterations and, if you agree, I'll merge.

Thanks!

2024-09-15 05:46 UTC, anderbubble approved these changes

2024-09-18 03:27 UTC, anderbubble commented
Rebased to main again.

2024-09-18 03:28 UTC, anderbubble commented
@mslacken and @JasonYangShadow could you look this over with my changes and let me know what you think?

2024-09-18 06:53 UTC, mslacken commented
What is the flag now doing? It's unrelated from the change from ctime to mtime.

2024-09-18 13:38 UTC, anderbubble commented
The `--syncuser` flag didn't exist on `wwctl container shell` before; with this change it accepts it and passes it through to `wwctl container exec`, so it behaves the same as that.

The flag change is unrelated to the mtime change, yes. Do you want that split into 2 PRs?

2024-09-20 22:35 UTC, anderbubble commented
@JasonYangShadow or @mslacken if either of you sign off on this, I'll go ahead and merge it. :)

2024-09-20 22:46 UTC, JasonYangShadow commented
> @JasonYangShadow or @mslacken if either of you sign off on this, I'll go ahead and merge it. :)

I am okay with this PR

2024-09-23 17:32 UTC, merged