cache dir and clean for 4.5.x
warewulf/warewulf pull request #1460
Opened 2024-10-21 13:39 UTC by mslacken

## Description of the Pull Request (PR):

Write your description of the PR here. Be sure to include as much background,
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.

## This fixes or addresses the following GitHub issues:

- Fixes #

## Reviewer  checklist

The reviewer checks the following items before merging the PR.

- [ ] The PR is based on the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [ ] All commits are "Signed off" (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [ ] The [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) has been updated, if necessary, and under the correct release heading
- [ ] The [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) have been updated, if necessary
- [ ] The submitter is listed in the [contributors file](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)

2024-10-21 15:39 UTC, anderbubble commented
@mslacken in a previous TSC meeting we discussed not doing any further v4.5.x releases. Is this a high-priority that needs to go out as a v4.5.9, or can we just prioritize v4.6.0?

2024-10-21 16:35 UTC, mslacken commented
I needed this for the openSUSE package anyway, so I didn't know that we are that strict on this. You can close it.

2024-10-24 06:26 UTC, mslacken commented
The oci cache isn't cleaned at all, so I needed a point to start with. We can also clean up the cache after container import and so there wouldn't be a need for an explicit cache directory. @anderbubble what are your thoughts?

2024-10-24 15:50 UTC, anderbubble commented
I'll try to review today, or tomorrow at the latest.

2024-10-28 21:24 UTC, anderbubble requested changes
@mslacken if you want this in v4.5.x, can you update it to match #1459?

2025-02-07 08:13 UTC, closed without merging