fix issue that initrd fails at downloading runtime overlay with permission denied error, when warewulf secure option in warewulf.conf is enabled
warewulf/warewulf pull request #1461
Opened 2024-10-22 07:56 UTC by JasonYangShadow

## Description of the Pull Request (PR):

fix issue that initrd fails at downloading runtime overlay with permission denied error, when warewulf secure option in warewulf.conf is enabled

## This fixes or addresses the following GitHub issues:

- Fixes #806

## Reviewer  checklist

The reviewer checks the following items before merging the PR.

- [ ] The PR is based on the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [ ] All commits are "Signed off" (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [ ] The [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) has been updated, if necessary, and under the correct release heading
- [ ] The [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) have been updated, if necessary
- [ ] The submitter is listed in the [contributors file](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)

## Test
Before:

![2024-10-22_16-31](https://github.com/user-attachments/assets/951cf983-53f5-43fe-bbee-3a2d58788872)

After:

![2024-10-22_16-40](https://github.com/user-attachments/assets/2d14141a-04f5-49c1-957e-380ebeca7772)

2024-10-25 21:24 UTC, anderbubble commented
@JasonYangShadow did it actually finish booting successfully for you? When I try, I get an error that it can't find the runtime initrd.

<img width="1392" alt="Screenshot 2024-10-25 at 3 22 55 PM" src="https://github.com/user-attachments/assets/e7fdf97e-9c19-4534-9688-7b39d25f35d5">

2024-10-25 21:26 UTC, anderbubble requested changes
Looks like it still can't boot in this state, because `initrd=runtime` points to a "file" that does not exist.

2024-10-28 08:05 UTC, mslacken approved these changes

2024-10-28 15:14 UTC, anderbubble commented
@mslacken did this fix the issue for you? It's still not able to boot for me.

2024-10-30 06:09 UTC, JasonYangShadow commented
> Looks like it still can't boot in this state, because `initrd=runtime` points to a "file" that does not exist.

cc @mslacken 
let me do another test with the new set up environment. Hold until the bug fix also works for @anderbubble

2024-10-30 11:44 UTC, JasonYangShadow commented
@anderbubble 
I tested again, it looks like it works

Node screenshots 
![2024-10-30_20-40](https://github.com/user-attachments/assets/ded91b2e-6567-48ad-8905-b4ed7ce3eab6)
![2024-10-30_20-41](https://github.com/user-attachments/assets/a007eac4-ca8a-44fd-98e9-541b7f0270da)
![2024-10-30_20-41_1](https://github.com/user-attachments/assets/f14bf78e-4e94-4b7b-8716-d0f6a949055d)

Host `/var/log/warewulf.log`
![2024-10-30_20-41_2](https://github.com/user-attachments/assets/afa284f2-bbb9-4314-9f54-e6e9c2716afc)

2024-10-30 15:27 UTC, anderbubble commented
@JasonYangShadow are you possibly testing in a BIOS environment rather than an EFI environment?

2024-10-31 02:33 UTC, anderbubble requested changes
Please confirm testing with EFI vs BIOS.

2024-11-08 03:49 UTC, JasonYangShadow commented
> Please confirm testing with EFI vs BIOS.

sorry for the late update.
It looks like that I am still able to boot into the VM using UEFI (if my setup is correct)

boot screen
![image](https://github.com/user-attachments/assets/6a8ad5e6-4c65-4021-b7c7-67cc020dad89)

error skip
![image](https://github.com/user-attachments/assets/8dae858f-b944-4723-b024-e7701ba6d9ce)

setup:
```
               compute.cpu_mode = 'host-passthrough'
                compute.memory = '16384'
                compute.cpus = '2'
                boot_network = {'network' => 'pxe'}
                compute.boot boot_network
		compute.loader = "/usr/share/edk2/ovmf/OVMF_CODE.fd"
		compute.nvram = "/usr/share/edk2/ovmf/OVMF_VARS.fd"
		compute.machine_arch = "x86_64"
		compute.machine_type = "q35"
```

a screen record for the boot
https://github.com/user-attachments/assets/82d5cfe6-068b-468e-8ada-1a614cb2bcc1

2024-11-14 05:22 UTC, anderbubble commented
@JasonYangShadow I made a change that prevents loading `initrd=runtime` if it couldn't be downloaded. This fixes the issue on my end. Can you confirm that it still works in your environment / let me know if you have any concerns with it? If it looks ok to you, I'll merge.

2024-11-14 05:23 UTC, anderbubble approved these changes

2024-11-14 05:36 UTC, JasonYangShadow commented
> @JasonYangShadow I made a change that prevents loading `initrd=runtime` if it couldn't be downloaded. This fixes the issue on my end. Can you confirm that it still works in your environment / let me know if you have any concerns with it? If it looks ok to you, I'll merge.

retested, still works!
![image](https://github.com/user-attachments/assets/644b348a-80a2-4cda-bc9d-add6d9752987)
![image](https://github.com/user-attachments/assets/c57cef34-8cfe-4d86-92a0-393a49e5bba2)
![image](https://github.com/user-attachments/assets/029d6063-f3ac-42ef-b257-1ef0ed46ed92)
![image](https://github.com/user-attachments/assets/f86d7b28-a6bc-4139-ac74-2e46f8f4deb4)

2024-11-14 06:11 UTC, anderbubble commented
Great! Thanks!

2024-11-14 06:11 UTC, merged