Persisten ndoe installer
warewulf/warewulf pull request #1557
Opened 2024-11-18 14:00 UTC by mslacken

## Persisten node installer base on dracut

Uses the dracut boot mode of warewulf and dumps the noed image not
to a tmpfs, but to a root fs on disk.
For the dik configuration ignition is used and also adds an additional 
`rsync` command to manage this service, so that not on every reboot
the node needs to be fully installed again.

## Reviewer  checklist

The reviewer checks the following items before merging the PR.

- [ ] The PR is based on the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [ ] All commits are "Signed off" (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [ ] The [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) has been updated, if necessary, and under the correct release heading
- [ ] The [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) have been updated, if necessary
- [ ] The submitter is listed in the [contributors file](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)
- [ ] The test suite has been updated, if necessary

2024-11-20 16:38 UTC, mslacken commented
@anderbubble In order to get this working we need #815 merged as in the dracut boot process we need configurations from the controller.
@MiddelkoopT I hope this works with debian as we need dracut for this.

2024-11-23 15:38 UTC, MiddelkoopT commented on internal/app/wwctl/configure/rsync/root.go
> +		Short:                 "Manage and initialize DHCP",
Typo - should be "Manage and initialize rsync"

2024-11-23 17:57 UTC, MiddelkoopT commented
> @MiddelkoopT I hope this works with debian as we need dracut for this.

Debian and Ubuntu do not install a rsyncd system unit, breaking `wwctl container import`.  

Is this what you were asking/looking for?

I was able to get a Ubuntu node up and running again with your PR branch (I had refactored my code) but did not test the persistent node installer (yet).

2024-11-25 14:08 UTC, mslacken commented
> > @MiddelkoopT I hope this works with debian as we need dracut for this.
> 
> Debian and Ubuntu do not install a rsyncd system unit, breaking `wwctl container import`.
> 
> Is this what you were asking/looking for?
> 
> I was able to get a Ubuntu node up and running again with your PR branch (I had refactored my code) but did not test the persistent node installer (yet).

Thanks for testing this.
Does debian/ubuntu have a  different name for the `rsyncd` service? If yes you can configure this name in `warewulf.conf` under
```
rsync:
  systemd name: debian-rsync
```

2024-12-21 02:52 UTC, anderbubble requested changes
At a relatively high-level, I would want to change this implementation:

- Use kernel args `root`, `rootfstype`, and others already supported by dracut, and in their native way, to identify an existing storage device to write the image to, optionally formatting it if it isn't already. (I might want to abandon `root=wwinit`, also, if we can use a different way to identify that warewulf should be used to boot.)
- If we do support partition management, I'd want to at least also support cloud-init, rather than just ignition. But for a first implementation I think I'd just support deploying the image to a pre-defined storage device or partition.
- I think adding an rsync subsystem for this is too heavyweight and complex. Maybe that's the right thing eventually; but for a first implementation, I think we should just pull the existing cpio archive and extract it into the target disk, so that disk deployments work the same as image deployments.

2025-01-07 16:42 UTC, mslacken commented
> At a relatively high-level, I would want to change this implementation:
> 
>     * Use kernel args `root`, `rootfstype`, and others already supported by dracut, and in their native way, to identify an existing storage device to write the image to, optionally formatting it if it isn't already. (I might want to abandon `root=wwinit`, also, if we can use a different way to identify that warewulf should be used to boot.)
> 

This might interfere with the dracut mechanics I am not aware of. So having a better or canonical way, if that way exists, would be better.

>     * If we do support partition management, I'd want to at least also support cloud-init, rather than just ignition. But for a first implementation I think I'd just support deploying the image to a pre-defined storage device or partition.
> 

Ignition is now a working concept, but if we find someone who adds the cloud-init stuff, I am happy to merge it.

>     * I think adding an rsync subsystem for this is too heavyweight and complex. Maybe that's the right thing eventually; but for a first implementation, I think we should just pull the existing cpio archive and extract it into the target disk, so that disk deployments work the same as image deployments.

No, without an incremental update a diskfull installation doesn't give us any benefits, as if you add any swap space, the tmpfs would swapped out quickly.

2025-01-09 19:22 UTC, mslacken commented
@anderbubble Did you have the chance to test this, yet?

2025-01-09 21:53 UTC, anderbubble commented
@mslacken I have not tried to use it yet; only reviewed (some of) the code to get an overview of how it is implemented.

2025-01-13 16:14 UTC, mslacken commented
@anderbubble When testing this code I got massive problems when using the kernel command line parameter `root=wwinit` as dracut tends to parse this parameter and fails with. This begs two questions:
1. How did the `dracut` boot method with the parameter `root=wwinit` work at all?
2. stick to `wwinit.mode={{ .Ipxe }}` as kernel parameter to find out if persistent boot is required

What do you think?

2025-01-27 13:57 UTC, mslacken commented
@anderbubble Can you please get on this as rebasing it to main costs more and more time.

2025-02-24 23:41 UTC, anderbubble commented
In anticipation of the upcoming release, I am reviewing open PRs that are not planned for inclusion in v4.6.0.

If you would like to pursue having this PR merged, plrease rebase it to current main, which is expected to largely match the v4.6.0 release. At that point, it can be reviewed for incorporation into an upcoming v4.6.x release.

2025-03-10 15:55 UTC, mslacken commented
@anderbubble I would like this merged as soon as possible. 
The refactoring and logging of the init code broke this completely and I had to spend a lot of time to get this running again.
Also the rename of container to image had to reflected in the code.

2025-03-19 19:46 UTC, mslacken commented
close #1821

2025-03-25 00:09 UTC, anderbubble commented
Rebased to main.

2025-03-26 00:55 UTC, anderbubble requested changes
I've reviewed this again. I've made a few small comments; but I think all of my original concerns remain. To emphasize

- I don't think the first implementation of this should be based on rsync. I think we need a working demonstration that uses the existing cpio method first.
- I'm concerned about using rsync for this at all, since that breaks the "image build" paradigm our users expect so far. Right now, changes don't get applied to compute nodes unless the image is "built." This breaks that expectation, as changes are made immediately. (Literally while you're still in a `wwctl image shell` session, even.)
- This is all too hard-coded assuming ignition, which isn't available in Rocky Linux 8 for one, and shouldn't be the only path forward in the long term.
- I find the process difficult to follow. For evenual approval, I think it'd be good to have a developer-side presentation in a TSC meeting walking us through how this works so that the whole committee can provide feedback.
- There shouldn't be special-casing of a named overlay: that would make it so that users can't control the behavior by specifying an overlay for the node or node's profile.

I don't pretend that my PRs are perfect, or always easy to understand, either, and I'm sorry for any frustration. But I don't feel good about merging this in its current state, and I think the best way to move forward would be to discuss it at the next TSC meeting.

2025-03-26 00:55 UTC, anderbubble commented on warewulf.spec.in
> +Warewulf server.
This needs to be merged with the `%package dracut` stanzas elsewhere in the file.

2025-03-26 00:55 UTC, anderbubble commented on overlays/wwroot/persistent/ignition.json.ww
> +{{ IgnitionJson }}
I don't think this needs to be in a bespoke `wwroot` overlay any more. It can just be pulled from the ignition overlay.

2025-03-26 00:55 UTC, anderbubble commented on internal/pkg/warewulfd/provision.go
> +				Ipxe:          remoteNode.Ipxe,
I don't see where this is used.

2025-03-26 00:55 UTC, anderbubble commented on dracut/modules.d/90wwinit/module-setup.sh
> +    echo network ignition
Since ignition isn't available in Rocky Linux 8, we'd at least need a way to make this optional.

2025-03-26 00:55 UTC, anderbubble commented on userdocs/server/bootloaders.rst
> +     --fsname rootfs --fsformat ext4 --fspath /rootfs
Doesn't this mean it will be mounted twice at runtime? Once by dracut at `/`, and again by systemd at `/rootfs`?

2025-03-26 00:55 UTC, anderbubble commented on etc/grub/grub.cfg.ww
> +menuentry "Two stage boot with dracut {{ if eq .Root "persistent"}}(persistent){{ end }}" --id dracut {
Don't make the menuentry dynamic: make a separate menuentry that is selected when persistent provisioning is desired.

2025-03-26 00:55 UTC, anderbubble commented on etc/grub/grub.cfg.ww
> +    configfile $conf
This should be removed.

2025-03-26 00:55 UTC, anderbubble commented on CHANGELOG.md
> +- Make dracut aware of `root==perisitent` which will install the node image to the parition `rootfs`
I think I said this before; but `root=persistent` is, imo, too generic. I already think the current `root=wwinit` is too generic; maybe `root=wwinit:tmpfs` would be better, then maybe this could be `root=wwinit:ignition` which would leave room for `root=wwinit:cloud-init` in the future.

2025-03-26 00:55 UTC, anderbubble commented on internal/pkg/config/root.go
> +	RSYNC        *RSYNCConf    `yaml:"rsync,omitempty"`
This shouldn't be all-caps; just make it `Rsync`.

2025-03-28 17:24 UTC, mslacken commented
The first install is based on the cpio archive. Only the subsequent reboots will use rsync to get the changes to the nodes.
I totally understand and like the idea that only the image after it's build is "valid" for the nodes and I am also uncomfortable to break this idea. Still I also dislike the idea that we send the complete image over the network when we can do a rsync for the changes only.
For the ignition stuff, we also rely on it for the disk management in general so having it for the disk full installation is logical. Do you know any alternative here, which can go into a initrd without pulling a complete python stack?
So my take would be to hide the rsync command, so that the permanent rebasing ends and disable the rsync command line in the dracut section.
But lets discuss this in the next meeting.

2025-03-28 17:26 UTC, mslacken commented
I don't get the point where this relies on a named overlay, can you give me pointer to that?

2025-03-28 17:37 UTC, anderbubble commented
> I don't get the point where this relies on a named overlay, can you give me pointer to that?

`overlays/wwroot/persistent/ignition.json.ww` must be in `overlays/wwroot`, a statically-named overlay.

2025-06-30 19:50 UTC, anderbubble commented
Closing in favor of #1894.

2025-06-30 19:50 UTC, closed without merging