render template files several times
warewulf/warewulf pull request #814
Opened 2023-05-09 15:59 UTC by mslacken

This makes it possible to use something like {{ .IPAddress }} in variables,
so that e.g. the kernel commandline parameter can contain a reference to 
the ip address of the warewulf master host

2023-05-10 16:24 UTC, anderbubble commented
What if, in stead of rendering the whole template several times, we just process (some?) template variable values as templates themselves once before applying them to the overall template?

2023-06-11 01:51 UTC, griznog commented
I've been using this in my `ipxe` script for a while now to get the masters info into the kernel command line and it's always worked fine, not sure I understand what I'm missing out on with the way it already worked? Would this make it possible (assuming it's not already possible) to use the node ipaddr? That's actually a requirement to use the `dracut` networking to set up networking from a dracut produced `initrd` via the kernel command line. 

```
boot kernel initrd=initrd.magic rootfs=tmpfs rootfstype=tmpfs wwid={{.Id}} wwcluster={{.Cluster}} wwcontainer={{.ContainerName}} {{.KernelArgs}} 
```

2023-10-11 10:11 UTC, mslacken commented
close #505

2024-10-30 18:39 UTC, anderbubble requested changes
@mslacken if you'd still like this included, can you rebase on main?

2024-11-04 18:07 UTC, closed without merging