Simple prometheus exporter
warewulf/warewulf pull request #899
Opened 2023-08-18 15:41 UTC by mslacken

Added a simple Prometheus exporter which uses the
data from `wwctl node status`
Additionally to that the container sizes are exported.
This PR is based #859 and can be merged afterwards.

2024-09-11 22:07 UTC, anderbubble commented
@mslacken this will need to be rebased if you want to get it in for v4.6.0; but, of course, probably waiting on #1020.

2024-10-31 02:35 UTC, anderbubble requested changes
@mslacken can you rebase this on main?

2025-02-24 23:39 UTC, anderbubble commented
In anticipation of the upcoming v4.6.0 release, I am reviewing open PRs that are not currently associated with a release milestone.

If you would like to pursue having this PR merged, plrease rebase it to current main, which is expected to largely match the v4.6.0 release. At that point, it can be reviewed for incorporation into an upcoming v4.6.x release.

2026-05-07 07:17 UTC, mslacken commented
not rebasing this one

2026-05-07 07:17 UTC, closed without merging